site_name: Loop
repo_url: https://github.com/artiumd/loop

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    #- navigation.tabs
